name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Configure CMake
        run: cmake -DBUILD_TESTING=ON -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build
